# Configuración del backend para Netlify Identity
backend:
  name: netlify-identity

# Configuración de la biblioteca de medios de Cloudinary
media_library:
  name: cloudinary
  config:
    cloud_name: impacto-creativo

# Configuración del flujo de trabajo y la interfaz de usuario
publish_mode: editorial_workflow

# Colecciones de contenido (tus productos)
collections:
  - name: "catalogo"
    label: "Catálogo de Productos"
    folder: "_productos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nombre del Producto", name: "nombre", widget: "string"}
      - {label: "Precio", name: "precio", widget: "number", value_type: "float"}
      - {label: "Imagen", name: "imagen", widget: "image"}
      - {label: "Descripción Corta", name: "descripcion", widget: "string", required: false}
      - {label: "Categoría", name: "categoria", widget: "select", options: ["Tazas y Vasos", "Portaretratos y Cuadros", "Llaveros y Colgantes", "Remeras y Gorras", "Perfumes", "Otros Productos"]}
